export const CardTypes = {
	Instagram: "instagram",
	Twitter: "twitter",
	Linkedin: "linkedin",
	Facebook: "facebook",
	Youtube: "youtube",
	Twitch: "twitch",
	Discord: "discord",
	Telegram: "telegram",
	Spotify: "spotify",
};

export const keys = [
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
	"8",
	"9",
	"10",
	"11",
	"12",
	"13",
	"14",
	"15",
];

export const cardData = {
	lg: [
		{
			i: "1",
			isResizable: false,
			type: CardTypes.Spotify,
			size: "TALL",
			title: "My Playlist",
			songCount: 15,
			imageUrl: "https://placehold.co/400x400",
			x: 0,
			y: 0,
			w: 1,
			h: 2,
		},
		{
			i: "2",
			isResizable: false,
			type: CardTypes.Instagram,
			size: "SMALL",
			title: "Instagram",
			imageUrl: "https://placehold.co/400x400",
			x: 1,
			y: 0,
			w: 1,
			h: 1,
		},
		{
			i: "3",
			isResizable: false,
			type: CardTypes.Spotify,
			size: "MEDIUM",
			title: "Daily Mix",
			songCount: 25,
			imageUrl: "https://placehold.co/400x400",
			x: 2,
			y: 0,
			w: 2,
			h: 1,
		},
		{
			i: "4",
			isResizable: false,
			type: CardTypes.Instagram,
			size: "MEDIUM",
			title: "Instagram Feed",
			imageUrl: "https://placehold.co/400x400",
			x: 1,
			y: 1,
			w: 2,
			h: 1,
		},
		{
			i: "5",
			isResizable: false,
			type: CardTypes.Spotify,
			size: "SMALL",
			title: "New Releases",
			imageUrl: "https://placehold.co/400x400",
			x: 3,
			y: 1,
			w: 1,
			h: 1,
		},
		{
			i: "6",
			isResizable: false,
			type: CardTypes.Spotify,
			size: "TALL",
			title: "Artist Spotlight",
			songArtist: "Taylor Swift",
			imageUrl: "https://placehold.co/400x400",
			x: 0,
			y: 2,
			w: 1,
			h: 2,
		},
		{
			i: "7",
			isResizable: false,
			type: CardTypes.Instagram,
			size: "MEDIUM",
			title: "Instagram Stories",
			imageUrl: "https://placehold.co/400x400",
			x: 1,
			y: 2,
			w: 2,
			h: 1,
		},
		{
			i: "8",
			isResizable: false,
			type: CardTypes.Spotify,
			size: "MEDIUM",
			title: "Recommended",
			imageUrl: "https://placehold.co/400x400",
			x: 3,
			y: 2,
			w: 1,
			h: 1,
		},
		{
			i: "9",
			isResizable: false,
			type: CardTypes.Instagram,
			size: "SMALL",
			title: "Instagram Profile",
			imageUrl: "https://placehold.co/400x400",
			x: 1,
			y: 3,
			w: 1,
			h: 1,
		},
		{
			i: "10",
			isResizable: false,
			type: CardTypes.Spotify,
			size: "LARGE",
			title: "Your Top Songs",
			songs: [
				{ title: "Song 1", artist: "Artist 1", duration: "3:45" },
				{ title: "Song 2", artist: "Artist 2", duration: "2:30" },
				{ title: "Song 3", artist: "Artist 3", duration: "4:10" },
			],
			imageUrl: "https://placehold.co/400x400",
			x: 2,
			y: 3,
			w: 2,
			h: 2,
		},
		{
			i: "11",
			isResizable: false,
			type: CardTypes.Instagram,
			size: "TALL",
			title: "Instagram Highlights",
			imageUrl: "https://placehold.co/400x400",
			x: 0,
			y: 4,
			w: 1,
			h: 2,
		},
		{
			i: "12",
			isResizable: false,
			type: CardTypes.Spotify,
			size: "MEDIUM",
			title: "Discover Weekly",
			imageUrl: "https://placehold.co/400x400",
			x: 1,
			y: 5,
			w: 2,
			h: 1,
		},
		{
			i: "13",
			isResizable: false,
			type: CardTypes.Instagram,
			size: "SMALL",
			title: "Instagram Reels",
			imageUrl: "https://placehold.co/400x400",
			x: 3,
			y: 5,
			w: 1,
			h: 1,
		},
		{
			i: "14",
			isResizable: false,
			type: CardTypes.Instagram,
			size: "MEDIUM",
			title: "Instagram Live",
			imageUrl: "https://placehold.co/400x400",
			x: 0,
			y: 6,
			w: 2,
			h: 1,
		},
		{
			i: "15",
			isResizable: false,
			type: CardTypes.Spotify,
			size: "MEDIUM",
			title: "Chill Vibes",
			imageUrl: "https://placehold.co/400x400",
			x: 2,
			y: 6,
			w: 2,
			h: 1,
		},
	],
};
