export const CardTypes = {
	Instagram: "instagram",
	Twitter: "twitter",
	Linkedin: "linkedin",
	Facebook: "facebook",
	Youtube: "youtube",
	Twitch: "twitch",
	Discord: "discord",
	Telegram: "telegram",
	Spotify: "spotify",
};

export const cardData = {
	lg: [
		{
			i: "1",
			isResizable: true,
			type: CardTypes.Spotify,
			size: "TALL",
			title: "My Playlist",
			songCount: 15,
			imageUrl: "https://placehold.co/400x400",
			x: 3,
			y: 3,
			w: 1,
			h: 2,
		},
		{
			i: "2",
			isResizable: false,
			type: CardTypes.Instagram,
			size: "SMALL",
			title: "Instagram",
			imageUrl: "https://placehold.co/400x400",
			x: 1,
			y: 0,
			w: 1,
			h: 1,
		},
		{
			i: "3",
			isResizable: false,
			type: CardTypes.Spotify,
			size: "MEDIUM",
			title: "Daily Mix",
			songCount: 25,
			imageUrl: "https://placehold.co/400x400",
			x: 2,
			y: 0,
			w: 2,
			h: 1,
		},
		{
			i: "4",
			isResizable: false,
			type: CardTypes.Instagram,
			size: "MEDIUM",
			title: "Instagram Feed",
			imageUrl: "https://placehold.co/400x400",
			x: 1,
			y: 1,
			w: 2,
			h: 1,
		},
	],
};
